server {
    listen 80 default_server;
    server_name _;
    index index.php index.html;
    root /code;
    location / {
        if (!-e $request_filename) {
            add_header Content-Type: 'text/html';
            return 200 $hostname;
        }
    }
}