server {
    listen 91 default_server;
    server_name _;
    index index.php index.html;
    root /code/apiserverWorkSpace92/ucApiserver/public;
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass container-php-fpm9272:9000;
    }
}
server {
    listen 92 default_server;
    server_name _;
    index index.php index.html;
    root /code/bookanapi92/opapi/public;
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass container-php-fpm9272:9000;
    }
}
server {
    listen 81 default_server;
    server_name _;
    index index.php index.html;
    root /code/bookanapi92/ucDbserver/public;
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass container-php-fpm9272:9000;
    }
}
server {
    listen 82 default_server;
    server_name _;
    index index.php index.html;
    root /code/bookanapi92/opdb/public;
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass container-php-fpm9272:9000;
    }
}
server {
    listen 71 default_server;
    server_name _;
    index index.php index.html;
    root /code/apiserverWorkSpace/ucApiserver/public;
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass container-php-fpm9272:9000;
    }
}
server {
    listen 72 default_server;
    server_name _;
    index index.php index.html;
    root /code/bookanapi/opapi/public;
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass container-php-fpm9272:9000;
    }
}
server {
    listen 61 default_server;
    server_name _;
    index index.php index.html;
    root /code/bookanapi/ucDbserver/public;
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass container-php-fpm9272:9000;
    }
}
server {
    listen 62 default_server;
    server_name _;
    index index.php index.html;
    root /code/bookanapi/opdb/public;
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass container-php-fpm9272:9000;
    }
}