# test sql: insert test,host=127.0.0.1,monitor_name=test count=1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      nodeName: ip-172-31-47-101
      containers:
        - name: influxdb
          image: influxdb:1.8.3
          ports:
            - containerPort: 8086
              protocol: TCP
          env:
            - name: INFLUXDB_DB
              value: mydb
            - name: INFLUXDB_HTTP_AUTH_ENABLED
              value: 'true'
            - name: INFLUXDB_ADMIN_USER
              value: admin
            - name: INFLUXDB_ADMIN_PASSWORD
              value: cx123456
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-influxdb
  labels:
    app: influxdb
spec:
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    app: influxdb