apiVersion: v1
kind: Pod
metadata:
  name: test-ebs
spec:
  containers:
  - image: busybox
    name: test-container
    volumeMounts:
    - mountPath: /test-eb
      name: test-volume
  volumes:
  - name: test-volume
    awsElasticBlockStore:
      volumeID: vol-0cae13614236d2f8b
      fsType: ext4
