kind: Deployment
metadata:
  name: traefik
  namespace: kube-system
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: traefik
        ports:
        - containerPort: 8080
          name: dash
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: tool.ivu1314.com
    http:
      paths:
      - path: /traefik/
        backend:
          serviceName: traefik
          servicePort: dash

