apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: tool.ivu1314.com
    http:
      paths:
      - backend:
          serviceName: traefik
          servicePort: dash

