server {
    listen 71 default_server;
    listen [::]:71 default_server;
    server_name _;
    index index.php index.html;
    root /code/apiserverWorkSpace/ucApiserver/public;
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass container-php-fpm7172:9000;
    }
}
server {
    listen 72 default_server;
    listen [::]:72 default_server;
    server_name _;
    index index.php index.html;
    root /code/apiserverWorkSpace/opApiserver/public;
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass container-php-fpm7172:9000;
    }
}
server {
    listen 81 default_server;
    listen [::]:81 default_server;
    server_name _;
    index index.php index.html;
    root /code/dbserverWorkSpace/ucDbserver/public;
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass container-php-fpm7172:9000;
    }
}
server {
    listen 82 default_server;
    listen [::]:82 default_server;
    server_name _;
    index index.php index.html;
    root /code/dbserverWorkSpace/opDbserver/public;
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass container-php-fpm7172:9000;
    }
}