apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul-server
spec:
  serviceName: consul-server
  selector:
    matchLabels:
      app: consul
  replicas: 2
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: consul:1.13.2
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "1"
          args: ["agent", "-server", "-join=consul-server-0", "-join=consul-server-1", "-retry-join=consul-server-0.consul-server", "-retry-join=consul-server-1.consul-server", "-client=0.0.0.0"]
          ports:
            - containerPort: 8300
            - containerPort: 8301
            - containerPort: 8302
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul-client
spec:
  serviceName: consul-client
  selector:
    matchLabels:
      app: consul
  replicas: 1
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: consul:1.13.2
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "1"
          args: ["agent", "-client", "-retry-join=consul-server-0.consul-server", "-retry-join=consul-server-1.consul-server", "-client=0.0.0.0"]
          ports:
            - containerPort: 8300
            - containerPort: 8301
            - containerPort: 8302
---
apiVersion: v1
kind: Service
metadata:
  name: consul-server
spec:
  clusterIP: None
  selector:
    app: consul
  ports:
    - port: 8300
      name: p8300
    - port: 8301
      name: p8301
    - port: 8302
      name: p8302