apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nas
  labels:
    alicloud-pvname: pv-nas
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeHandle: pv-nas
    volumeAttributes:
      server: "1825d4a3d0-hec6.cn-beijing.nas.aliyuncs.com"
      path: "/csi"
  mountOptions:
    - nolock,tcp,noresvport
    - vers=3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      alicloud-pvname: pv-nas
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
data:
  master.cnf: |
    [mysqld]
    log-bin
  slave.cnf: |
    [mysqld]
    super-read-only
  start.sh: |
    [[ `hostname` =~ -[1-9]$ ]] || exit 0
    until mysql -e "select 1"; do sleep 1; done
    mysql -e "show slave status" | grep Slave || mysql -e " \
    change master to master_host='mysql-0.mysql',master_user='root',master_password=''; \
    start slave; \
    "
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
        - name: init-mysql
          image: mysql:5.7
          args:
            - bash
            - -c
            - |
              set -ex
              ordinal=`hostname | tr -cd "[0-9]"`
              basedir=/mnt/mysql/mysql_${ordinal}
              if [[ $ordinal -eq 0 ]]; then
                cp /etc/config-map/master.cnf /etc/mysql/mysql.conf.d
              else
                cp /etc/config-map/slave.cnf /etc/mysql/mysql.conf.d
              fi
              echo -e '[mysqld]\nserver-id='$((100 + $ordinal)) >> /etc/mysql/mysql.conf.d/server-id.cnf
              echo -e '\nbasedir='${basedir} >> /etc/mysql/mysql.conf.d/server-id.cnf
              echo -e '\ndatadir='${basedir}/data >> /etc/mysql/mysql.conf.d/server-id.cnf
              mkdir -p $basedir
          volumeMounts:
            - name: persistent-storage
              mountPath: /mnt/mysql
              subPath: mysql
            - name: mysql-conf
              mountPath: /etc/mysql/mysql.conf.d
            - name: config-map
              mountPath: /etc/config-map
      containers:
        - name: mysql
          image: mysql:5.7
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "1"
          lifecycle:
            postStart:
              exec:
                command:
                  - bash
                  - -x
                  - /etc/config-map/start.sh
          args:
            - "--ignore-db-dir=lost+found"
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: persistent-storage
              mountPath: /mnt/mysql
              subPath: mysql
            - name: mysql-conf
              mountPath: /etc/mysql/mysql.conf.d
            - name: config-map
              mountPath: /etc/config-map
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: nas-claim
        - name: mysql-conf
          emptyDir: {}
        - name: config-map
          configMap:
            name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
spec:
  ports:
    - name: mysql
      port: 3306
  clusterIP: None
  selector:
    app: mysql