# 阿里的ask需要先设置NAT才能访问外网：https://help.aliyun.com/document_detail/99146.html
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-demo-mp
data:
  index.html: |
    hello
    <b>world<b>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-deploy
spec:
  selector:
    matchLabels:
      app: nginx-demo-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-demo-pod
    spec:
      volumes:
        - name: nginx-demo-volume
          configMap:
            name: nginx-demo-mp
      containers:
        - name: nginx-demo-pod
          image: nginx:1.15-alpine
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-demo-volume
              mountPath: /usr/share/nginx/html/nginx
      imagePullSecrets:
        - name: my-secret
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
  labels:
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 80
      protocol: TCP
      name: https
  selector:
    app: nginx-demo-pod
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-demo-ing
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-id: lb-2zeck3xgr61ops6rhf4px
    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: "true"
spec:
  rules:
    - http:
        paths:
          - path: /nginx/
            backend:
              serviceName: nginx-demo
              servicePort: 80
